#ifndef _ERRORNAMEDEF_H_
#define _ERRORNAMEDEF_H_

#include <windows.h>

enum _ErrorNameDef_
{
	/////////////////////////////////////////////////////////////////////
	// 1~49 : 중요 에러..
	/////////////////////////////////////////////////////////////////////
	ER_EMG					= 1,
	ER_MAIN_AIR				= 2,
	
	ER_FIRE_MONITORING		= 7,
	
	ER_ROUTER_IONIZER_01	= 9,
	ER_ROUTER_IONIZER_02	= 10,
	ER_ROUTER_IONIZER_03	= 11,
	ER_ROUTER_IONIZER_04	= 12,
	
	ER_SAFETY_BEAM_LD		 = 17,
	ER_SAFETY_BEAM_SCRAP_BOX = 18,

	ER_TENKEY_POS_ROUTER_CYCLE_TM_OVER = 20, 
	ER_TENKEY_POS_VISION_CYCLE_TM_OVER = 21, 

	ER_INDEX1_AIR_FLOW_IS_LOW	= 30,
	ER_INDEX2_AIR_FLOW_IS_LOW	= 31, 
	ER_INDEX3_AIR_FLOW_IS_LOW	= 32, 
	ER_INDEX4_AIR_FLOW_IS_LOW	= 33, 
	/////////////////////////////////////////////////////////////////////
	// 50~99 : Door, SafetyBeam..
	/////////////////////////////////////////////////////////////////////
	ER_DOOR_OPEN			= 50,
	ER_DOOR_OPEN_01			= 51, 
	ER_DOOR_OPEN_02			= 52, 
	ER_DOOR_OPEN_03			= 53, 
	ER_DOOR_OPEN_04			= 54, 
	ER_DOOR_OPEN_05			= 55, 
	ER_DOOR_OPEN_06			= 56, 
	ER_DOOR_OPEN_07			= 57, 
	ER_DOOR_OPEN_08			= 58, 
	ER_DOOR_OPEN_09			= 59, 
	ER_DOOR_OPEN_10			= 60, 
	ER_DOOR_OPEN_11			= 61, 
	ER_DOOR_OPEN_12			= 62, 
	ER_DOOR_OPEN_13			= 63, 
	ER_DOOR_OPEN_14			= 64, 
	ER_DOOR_OPEN_15			= 65, 
	ER_DOOR_OPEN_16			= 66, 
	ER_DOOR_OPEN_17			= 67, 
	ER_DOOR_OPEN_18			= 68, 
	ER_DOOR_OPEN_19			= 69, 
	ER_DOOR_OPEN_20			= 70, 
	ER_DOOR_OPEN_21			= 71, 
	ER_DOOR_OPEN_22			= 72,
	ER_DOOR_OPEN_SCRAP_BOX	= 73,

	ER_DOOR_UNLOCK			= 80,
	ER_DOOR_UNLOCK_01		= 81,
	ER_DOOR_UNLOCK_02		= 82,
	ER_DOOR_UNLOCK_03		= 83,
	ER_DOOR_UNLOCK_04		= 84,
	ER_DOOR_UNLOCK_05		= 85,
	ER_DOOR_UNLOCK_06		= 86,
	ER_DOOR_UNLOCK_07		= 87,
	ER_DOOR_UNLOCK_08		= 88,
	ER_DOOR_UNLOCK_09		= 89,

	
	/////////////////////////////////////////////////////////////////////
	// 100~199 : Pneumatic
	/////////////////////////////////////////////////////////////////////
	ER_PNEUMATIC						= 100,
	ER_CYL_MGZ_IN_STOPPER_UD_01			= 101, 
	ER_CYL_MGZ_IN_STOPPER_UD_02			= 102, 
	ER_CYL_MGZ_IN_STOPPER_UD_03			= 103, 
	ER_CYL_MGZ_LOAD_STOPPER_UD			= 104,
	ER_CYL_MGZ_OUT_STOPPER_FB_01		= 105,
	ER_CYL_MGZ_OUT_STOPPER_FB_02		= 106,	

	ER_CYL_MGZ_CLAMP_OC					= 108,
	ER_CYL_MGZ_CLAMP_ALIGN_FB			= 109,
	ER_CYL_RAIL_GRIPPER_OC				= 110,
	ER_SOL_INDEX_STAGE_KIT_OC_01		= 111,
	ER_SOL_INDEX_STAGE_KIT_OC_02		= 112,
	ER_SOL_INDEX_STAGE_KIT_OC_03		= 113,
	ER_SOL_INDEX_STAGE_KIT_OC_04		= 114,
	ER_CYL_INDEX_DUST_SHUTTER_OC_01		= 115,
	ER_CYL_INDEX_DUST_SHUTTER_OC_02		= 116,
	ER_CYL_INDEX_DUST_SHUTTER_OC_03		= 117,
	ER_CYL_INDEX_DUST_SHUTTER_OC_04		= 118,
	ER_SOL_INDEX_STAGE_AIR_BLOW_0102	= 119,
	ER_SOL_INDEX_STAGE_AIR_BLOW_0304	= 120,
	ER_CYL_INDEX_MASK_KIT_FIX_L_FB_01	= 121,
	ER_CYL_INDEX_MASK_KIT_FIX_R_FB_01	= 122,
	ER_CYL_INDEX_MASK_KIT_FIX_UD_01		= 123,
	ER_CYL_INDEX_MASK_KIT_FIX_L_FB_02	= 124,
	ER_CYL_INDEX_MASK_KIT_FIX_R_FB_02	= 125,
	ER_CYL_INDEX_MASK_KIT_FIX_UD_02		= 126,
	ER_CYL_INDEX_MASK_KIT_FIX_L_FB_03	= 127,
	ER_CYL_INDEX_MASK_KIT_FIX_R_FB_03	= 128,
	ER_CYL_INDEX_MASK_KIT_FIX_UD_03		= 129,
	ER_CYL_INDEX_MASK_KIT_FIX_L_FB_04	= 130,
	ER_CYL_INDEX_MASK_KIT_FIX_R_FB_04	= 131,
	ER_CYL_INDEX_MASK_KIT_FIX_UD_04		= 132,
	ER_CYL_MASK_KIT_PICKER_UD_01		= 133,
	ER_CYL_MASK_KIT_PICKER_UD_02		= 134,
	ER_CYL_MASK_KIT_PICKER_UD_03		= 135,
	ER_CYL_MASK_KIT_PICKER_UD_04		= 136,
	ER_CYL_MASK_KIT_PICKER_OC_01		= 137,
	ER_CYL_MASK_KIT_PICKER_OC_02		= 138,	
	ER_CYL_MASK_KIT_PICKER_OC_03		= 139,
	ER_CYL_MASK_KIT_PICKER_OC_04		= 140,
	ER_CYL_ROUTER_BIT_CHANGE_CLAMP_UD_01= 141, 	
	ER_CYL_ROUTER_BIT_CHANGE_CLAMP_UD_02= 142, 
	ER_CYL_ROUTER_BIT_CHANGE_CLAMP_OC_01= 143, 
	ER_CYL_ROUTER_BIT_CHANGE_CLAMP_OC_02= 144, 
	ER_SOL_SPD_AIR_BLOW_0102			= 145, 
	ER_SOL_SPD_AIR_BLOW_0304			= 146, 
	ER_SOL_SPD_CHUCK_OC_01				= 147,
	ER_SOL_SPD_CHUCK_OC_02				= 148,
	ER_SOL_SPD_CHUCK_OC_03				= 149,
	ER_SOL_SPD_CHUCK_OC_04				= 150,
	ER_SOL_ROUTER_IONIZER_01			= 151,
	ER_SOL_ROUTER_IONIZER_02			= 152,
	ER_SOL_ROUTER_IONIZER_03			= 153,
	ER_SOL_ROUTER_IONIZER_04			= 154,
	ER_VAC_OUTPNP						= 155,
	ER_VAC_OUTPNP_EJECT					= 156,
	ER_CYL_OUTPNP_SCRAP_OC_F			= 157,
	ER_CYL_OUTPNP_SCRAP_OC_R			= 158,
	ER_CYL_OUTPNP_SCRAP_UD				= 159,
	ER_CYL_OUTPNP_SCRAP_FIX_UD_F		= 160,
	ER_CYL_OUTPNP_SCRAP_FIX_UD_R		= 161,	
	ER_SOL_OUTPNP_KIT_CLAMP_OC			= 162,	
	ER_SPINDLE_F_01						= 163,	
	ER_SPINDLE_R_01						= 164, 

	ER_CYL_RAIL_GRIPPER_FB				= 165,

	ER_SPINDLE_F_02						= 166,
	ER_SPINDLE_R_02						= 167, 

	
	/////////////////////////////////////////////////////////////////////
	// 200~249 : Motor Alarm
	/////////////////////////////////////////////////////////////////////
	ER_MT_ALARM										= 200,  
	ER_MT_INDEX_X_01_ALARM							= 201,  
	ER_MT_INDEX_X_02_ALARM							= 202,  
	ER_MT_INDEX_X_03_ALARM							= 203,  
	ER_MT_INDEX_X_04_ALARM							= 204,  
	ER_MT_INDEX_T_01_ALARM							= 205,  
	ER_MT_INDEX_T_02_ALARM							= 206,  
	ER_MT_INDEX_T_03_ALARM							= 207,  
	ER_MT_INDEX_T_04_ALARM							= 208, 
	ER_MT_ROUTER_Y_01_ALARM							= 209,  
	ER_MT_ROUTER_Y_02_ALARM							= 210,  
	ER_MT_ROUTER_W_01_ALARM							= 211,  
	ER_MT_ROUTER_W_02_ALARM							= 212,  
	ER_MT_SPINDLE_Z_01_ALARM						= 213,  
	ER_MT_SPINDLE_Z_02_ALARM						= 214,  
	ER_MT_SPINDLE_Z_03_ALARM						= 215,  
	ER_MT_SPINDLE_Z_04_ALARM						= 216,
	ER_MT_MGZ_LOAD_Z_ALARM							= 217,
	ER_MT_PUSHER_X_ALARM							= 218,  
	ER_MT_RAIL_GRIPPER_X_ALARM						= 219,  
	ER_MT_LD_Y_ALARM								= 220,  
	ER_MT_LD_Z_ALARM								= 221,  
	ER_MT_OUT_PNP_Y_ALARM							= 222,  
	ER_MT_OUT_PNP_Z_ALARM							= 223,  
	ER_MT_OUT_PNP_X_ALARM							= 224,
	ER_MT_IN_PNP_CLAMP_Y_ALARM						= 225, 
	ER_MT_IN_PNP_Y_ALARM							= 226,  
	ER_MT_IN_PNP_Z_ALARM							= 227,  
	ER_MT_ADC_Z_ALARM								= 228, 
	ER_MT_ADC_X_ALARM								= 229,



	/////////////////////////////////////////////////////////////////////
	// 300~349 : Servo Off						 
	/////////////////////////////////////////////////////////////////////
	ER_MT_SERVO_OFF									= 300, 
	ER_MT_INDEX_X_01_SERVO_OFF						= 301,  
	ER_MT_INDEX_X_02_SERVO_OFF						= 302, 
	ER_MT_INDEX_X_03_SERVO_OFF						= 303,  
	ER_MT_INDEX_X_04_SERVO_OFF						= 304,  
	ER_MT_INDEX_T_01_SERVO_OFF						= 305,  
	ER_MT_INDEX_T_02_SERVO_OFF						= 306,  
	ER_MT_INDEX_T_03_SERVO_OFF						= 307,  
	ER_MT_INDEX_T_04_SERVO_OFF						= 308,  
	ER_MT_ROUTER_Y_01_SERVO_OFF						= 309,  
	ER_MT_ROUTER_Y_02_SERVO_OFF						= 310,  
	ER_MT_ROUTER_W_01_SERVO_OFF						= 311,  
	ER_MT_ROUTER_W_02_SERVO_OFF						= 312,  
	ER_MT_SPINDLE_Z_01_SERVO_OFF					= 313,  
	ER_MT_SPINDLE_Z_02_SERVO_OFF					= 314,  
	ER_MT_SPINDLE_Z_03_SERVO_OFF					= 315,  
	ER_MT_SPINDLE_Z_04_SERVO_OFF					= 316,
	ER_MT_MGZ_LOAD_Z_SERVO_OFF						= 317,
	ER_MT_PUSHER_X_SERVO_OFF						= 318,  
	ER_MT_RAIL_GRIPPER_X_SERVO_OFF					= 319, 
	ER_MT_LD_Y_SERVO_OFF							= 320,
	ER_MT_LD_Z_SERVO_OFF							= 321,  
	ER_MT_OUT_PNP_Y_SERVO_OFF						= 322,  
	ER_MT_OUT_PNP_Z_SERVO_OFF						= 323,  
	ER_MT_OUT_PNP_X_SERVO_OFF						= 324,
	ER_MT_IN_PNP_CLAMP_Y_SERVO_OFF					= 325,   
	ER_MT_IN_PNP_Y_SERVO_OFF						= 326,  
	ER_MT_IN_PNP_Z_SERVO_OFF						= 327,  
	ER_MT_ADC_Z_SERVO_OFF							= 328, 
	ER_MT_ADC_X_SERVO_OFF							= 329, 



	/////////////////////////////////////////////////////////////////////
	// 350~399 : Limit Sensor					 
	/////////////////////////////////////////////////////////////////////
	ER_MT_LIMIT										= 350, 
	ER_MT_INDEX_X_01_LIMIT							= 351,  
	ER_MT_INDEX_X_02_LIMIT							= 352,  
	ER_MT_INDEX_X_03_LIMIT							= 353,  
	ER_MT_INDEX_X_04_LIMIT							= 354,  
	ER_MT_INDEX_T_01_LIMIT							= 355,  
	ER_MT_INDEX_T_02_LIMIT							= 356,  
	ER_MT_INDEX_T_03_LIMIT							= 357,  
	ER_MT_INDEX_T_04_LIMIT							= 358,  
	ER_MT_ROUTER_Y_01_LIMIT							= 359,  
	ER_MT_ROUTER_Y_02_LIMIT							= 360,  
	ER_MT_ROUTER_W_01_LIMIT							= 361,  
	ER_MT_ROUTER_W_02_LIMIT							= 362,
	ER_MT_SPINDLE_Z_01_LIMIT						= 363,  
	ER_MT_SPINDLE_Z_02_LIMIT						= 364,  
	ER_MT_SPINDLE_Z_03_LIMIT						= 365,  
	ER_MT_SPINDLE_Z_04_LIMIT						= 366,
	ER_MT_MGZ_LOAD_Z_LIMIT							= 367,
	ER_MT_PUSHER_X_LIMIT							= 368,  
	ER_MT_RAIL_GRIPPER_X_LIMIT						= 369,  
	ER_MT_LD_Y_LIMIT								= 370,  
	ER_MT_LD_Z_LIMIT								= 371,  
	ER_MT_OUT_PNP_Y_LIMIT							= 372,  
	ER_MT_OUT_PNP_Z_LIMIT							= 373,  
	ER_MT_OUT_PNP_X_LIMIT							= 374,
	ER_MT_IN_PNP_CLAMP_Y_LIMIT						= 375,  
	ER_MT_IN_PNP_Y_LIMIT							= 376,  
	ER_MT_IN_PNP_Z_LIMIT							= 377,  
	ER_MT_ADC_Z_LIMIT								= 378, 
	ER_MT_ADC_X_LIMIT								= 379,

	

	/////////////////////////////////////////////////////////////////////
	// 400~449 : Home
	/////////////////////////////////////////////////////////////////////
	ER_MT_HOME										= 400,  
	ER_MT_INDEX_X_01_HOME							= 401,  
	ER_MT_INDEX_X_02_HOME							= 402,  
	ER_MT_INDEX_X_03_HOME							= 403,  
	ER_MT_INDEX_X_04_HOME							= 404,  
	ER_MT_INDEX_T_01_HOME							= 405,  
	ER_MT_INDEX_T_02_HOME							= 406,  
	ER_MT_INDEX_T_03_HOME							= 407,  
	ER_MT_INDEX_T_04_HOME							= 408,  
	ER_MT_ROUTER_Y_01_HOME							= 409,  
	ER_MT_ROUTER_Y_02_HOME							= 410,  
	ER_MT_ROUTER_W_01_HOME							= 411,  
	ER_MT_ROUTER_W_02_HOME							= 412,  
	ER_MT_SPINDLE_Z_01_HOME							= 413,  
	ER_MT_SPINDLE_Z_02_HOME							= 414,  
	ER_MT_SPINDLE_Z_03_HOME							= 415,  
	ER_MT_SPINDLE_Z_04_HOME							= 416,
	ER_MT_MGZ_LOAD_Z_HOME							= 417,
	ER_MT_PUSHER_X_HOME								= 418,  
	ER_MT_RAIL_GRIPPER_X_HOME						= 419,  
	ER_MT_LD_Y_HOME									= 420,  
	ER_MT_LD_Z_HOME									= 421,  
	ER_MT_OUT_PNP_Y_HOME							= 422,  
	ER_MT_OUT_PNP_Z_HOME							= 423,  
	ER_MT_OUT_PNP_X_HOME							= 424,
	ER_MT_IN_PNP_CLAMP_Y_HOME						= 425,  
	ER_MT_IN_PNP_Y_HOME								= 426,  
	ER_MT_IN_PNP_Z_HOME								= 427,  
	ER_MT_ADC_Z_HOME								= 428, 
	ER_MT_ADC_X_HOME								= 429,


	ER_MT_INDIVIDUAL_HOME_LD_Y						= 431, // 210721 개별 홈 잡을때 에러
	ER_MT_INDIVIDUAL_HOME_LD_Z						= 432, // 210721
	ER_MT_INDEX_MOVE_LD_Y							= 433, // 210721 Index Move 시 에러
	ER_MT_INDEX_MOVE_LD_Z							= 434, // 210721

	ER_TIME_OVER_HOME_CYCLE							= 450,

	/////////////////////////////////////////////////////////////////////
	// 450~499 : Part Exist
	/////////////////////////////////////////////////////////////////////
//	ER_OHT_IN_EXIST							= 450, 
//	ER_OHT_OUT_EXIST						= 451, 
	ER_MZ_OUT_BUFFER_EXIST1					= 451, 
	ER_MZ_OUT_BUFFER_EXIST2					= 452, 
	ER_MZ_OUT_BUFFER_EXIST3					= 453, 
	ER_MZ_OUT_BUFFER_EXIST4					= 454, 
	ER_MZ_OUT_ARRIVAL_EXIST					= 455, 
//	ER_OHT_IN_JAM							= 454, 
	ER_LD_MZ_EXIST							= 456	,

	/////////////////////////////////////////////////////////////////////
	// 460 ~ : Out Pnp Add Error
	/////////////////////////////////////////////////////////////////////

	ER_OUTPNP_SCRAP_NOT_EXIST_INDEX_1		= 460, 
	ER_OUTPNP_SCRAP_NOT_EXIST_INDEX_2		= 461, 
	ER_OUTPNP_SCRAP_NOT_EXIST_INDEX_3		= 462, 
	ER_OUTPNP_SCRAP_NOT_EXIST_INDEX_4		= 463, 
	ER_OUTPNP_VAC_NOT_ON_INDEX_1			= 464, 
	ER_OUTPNP_VAC_NOT_ON_INDEX_2			= 465, 
	ER_OUTPNP_VAC_NOT_ON_INDEX_3			= 466, 
	ER_OUTPNP_VAC_NOT_ON_INDEX_4			= 467, 
	ER_CYL_OUTPNP_SCRAP_DW_INDEX_1			= 468, 
	ER_CYL_OUTPNP_SCRAP_DW_INDEX_2			= 469, 
	ER_CYL_OUTPNP_SCRAP_DW_INDEX_3			= 470, 
	ER_CYL_OUTPNP_SCRAP_DW_INDEX_4			= 471, 
	ER_CYL_OUTPNP_SCRAP_UP_INDEX_1			= 472, 
	ER_CYL_OUTPNP_SCRAP_UP_INDEX_2			= 473, 
	ER_CYL_OUTPNP_SCRAP_UP_INDEX_3			= 474, 
	ER_CYL_OUTPNP_SCRAP_UP_INDEX_4			= 475, 
	ER_CYL_OUTPNP_SCRAP_FIX_DW_INDEX_1		= 476, 
	ER_CYL_OUTPNP_SCRAP_FIX_DW_INDEX_2		= 477, 
	ER_CYL_OUTPNP_SCRAP_FIX_DW_INDEX_3		= 478, 
	ER_CYL_OUTPNP_SCRAP_FIX_DW_INDEX_4		= 479, 
	ER_CYL_OUTPNP_SCRAP_CLOSE_INDEX_1		= 480, 
	ER_CYL_OUTPNP_SCRAP_CLOSE_INDEX_2		= 481, 
	ER_CYL_OUTPNP_SCRAP_CLOSE_INDEX_3		= 482, 
	ER_CYL_OUTPNP_SCRAP_CLOSE_INDEX_4		= 483, 


	/////////////////////////////////////////////////////////////////////
	// 490~519 : Oht Part
	/////////////////////////////////////////////////////////////////////
	ER_ROUTER_LOAD_CHECK_TM_OVER_01				= 490, 
	ER_ROUTER_LOAD_CHECK_TM_OVER_02				= 491, 
	ER_ROUTER_LOAD_CHECK_TM_OVER_03				= 492, 
	ER_ROUTER_LOAD_CHECK_TM_OVER_04				= 493, 

// 	ER_OHT_IN_START_FAIL					= 490, 
// 	ER_OHT_IN_START_TM_OVER					= 491, 
// 	ER_OHT_OUT_START_FAIL					= 492, 
// 	ER_OHT_OUT_START_TM_OVER				= 493, 
// 	ER_OHT_IN_STOP_FAIL						= 494, 
// 	ER_OHT_IN_STOP_TM_OVER					= 495, 
// 	ER_OHT_OUT_STOP_FAIL					= 496, 
// 	ER_OHT_OUT_STOP_TM_OVER					= 497, 

// 	ER_OHT_IN_CYCLE_TM_OVER					= 500, 
// 	ER_OHT_OUT_CYCLE_TM_OVER				= 501, 
// 	ER_OHT_IN_CALL_CYCLE_TM_OVER			= 502, 
// 	ER_OHT_OUT_CALL_CYCLE_TM_OVER			= 503, 
// 	ER_OHT_STATUS_CYCLE_TM_OVER				= 504, 
// 	ER_OHT_PAUSED_STOP						= 505,
// 	ER_OHT_TR_REQ_TM_OVER					= 506,
// 	ER_OHT_BUSY_ON_TM_OVER					= 507,
// 	ER_OHT_BUSY_OFF_TM_OVER					= 508,
// 	ER_OHT_COMP_ON_TM_OVER					= 509,
// 	ER_OHT_COMP_OFF_TM_OVER					= 510,
// 	ER_OHT_IN_CALL_FAIL						= 511, 
// 	ER_OHT_OUT_CALL_FAIL					= 512, 
// 	ER_OHT_IN_CALL_TM_OVER					= 513, 
// 	ER_OHT_OUT_CALL_TM_OVER					= 514, 

	/////////////////////////////////////////////////////////////////////
	// 520~539 : Loader In Mgz Part
	/////////////////////////////////////////////////////////////////////
	ER_MZ_IN_STOPPER_CYCLE_TM_OVER			= 520, 
	ER_MZ_IN_STOPPER_STEP_CYCLE_TM_OVER		= 521, 
	ER_MZ_IN_CYCLE_TM_OVER					= 522,

	ER_MZ_LOAD_CYCLE_TM_OVER				= 523,
	ER_MZ_UNLOAD_CYCLE_TM_OVER				= 524,
	ER_MZ_LOADER_EXIST						= 525,
	ER_MZ_LOADER_ARRIVAL					= 526,
	ER_MZ_IN_ARRIVAL_EXIST					= 527, 
	ER_MZ_IN_STOPPER_1_EXIST				= 528, 
	ER_MZ_IN_STOPPER_2_EXIST				= 529, 
	ER_MZ_IN_STOPPER_3_EXIST				= 530, 
	ER_MZ_IN_LOADER_EXIST_NOT_ON			= 531, 
	ER_MZ_IN_LOADER_EXIST_NOT_OFF			= 532, 
	ER_MZ_IN_STOPPER_01_EXIST_NOT_ON		= 533, 
	ER_MZ_IN_STOPPER_01_EXIST_NOT_OFF		= 534, 
	ER_MZ_IN_STOPPER_02_EXIST_NOT_ON		= 535, 
	ER_MZ_IN_STOPPER_02_EXIST_NOT_OFF		= 536, 
	ER_MZ_IN_STOPPER_03_EXIST_NOT_ON		= 537, 
	ER_MZ_IN_STOPPER_03_EXIST_NOT_OFF		= 538, 
	ER_MZ_IN_JAM							= 539, 


	/////////////////////////////////////////////////////////////////////
	// 540~559 : Loader Out Mgz Part
	/////////////////////////////////////////////////////////////////////
	ER_MZ_OUT_CYCLE_TM_OVER					= 540, 
	ER_MZ_OUT_MANUAL_CYCLE_TM_OVER			= 541, 
	
//	ER_MZ_OUT_OHT_EXIST_NOT_ON				= 545, 
//	ER_MZ_OUT_OHT_EXIST_NOT_OFF				= 546, 
	ER_MZ_OUT_ARRIVAR_EXIST_NOT_ON			= 547, 

	ER_MZ_OUT_JAM							= 555,

	/////////////////////////////////////////////////////////////////////
	// 560~599 : Loader Mz Part
	/////////////////////////////////////////////////////////////////////
	ER_LD_MZ_LOADING_CYCLE_TM_OVER			= 560,
	ER_LD_MZ_ALIGN_CYCLE_TM_OVER			= 561,
	ER_LD_MZ_READ_RFID_CYCLE_TM_OVER		= 562,
	ER_LD_MZ_MERGE_INFO_CYCLE_TM_OVER		= 563,
	ER_LD_MZ_CARRIER_ID_READ_CYCLE_TM_OVER	= 564,
	ER_LD_MZ_PUSHER_CYCLE_TM_OVER			= 565,
	ER_LD_MZ_RFID_WRITE_CYCLE_TM_OVER		= 566, 
	ER_LD_MZ_EJECT_CYCLE_TM_OVER			= 567,
	ER_LD_MZ_TRAY_INFO_CYCLE_TM_OVER		= 568, 
	ER_LD_MZ_RFID_WRITE_CHECK_CYCLE_TM_OVER	= 569, 
	
	ER_LD_MZ_MTY_CANNOT_MOVE				= 570, 
	ER_LD_MZ_EXIST_SEN_NOT_ON				= 571, 
	ER_LD_MZ_READ_RFID_FAIL					= 572, 
	ER_LD_MZ_MERGE_INFO_TM_OVER				= 573, 
	ER_LD_MZ_MERGE_INFO_FAIL				= 574, 
	ER_LD_MZ_CARRIER_ID_READ_TM_OVER		= 575, 
	ER_LD_MZ_CARRIER_ID_READ_FAIL			= 576, 
	ER_LD_MZ_REWORK_LOT_MIX					= 577, 
	ER_LD_MZ_PUSHER_OVER_LOAD				= 578, 
	ER_LD_MZ_FAIL_RFID_WRITE				= 579, 
	ER_LD_MZ_TRAY_INFO_TM_OVER				= 580, 
	ER_LD_MZ_TRAY_INFO_FAIL					= 581, 
	ER_LD_MZ_FAIL_RFID_WRITE_CHECK			= 582, 
	ER_LD_MZ_LOT_CUR_QTY_DIFFERENT			= 583,		
	ER_LOADER_PCB_JAM						= 584,
	ER_PUSHER_X_NOT_BWD_POS					= 585,
												   
	ER_LD_MZ_CLAMP_PCB_JAM_NOT_OFF			= 590,
	ER_PART_NO_COMPARE_CYCLE_TM_OVER		= 591, 
	ER_AUTO_RECIPE_CHG_CYCLE_TM_OVER		= 592, 
	ER_PART_NO_COMPARE_TM_OVER				= 593, 
	ER_PART_NO_DIFFERENT					= 594, 
	ER_AUTO_RECIPE_CHG_TM_OVER				= 595, 
	ER_AUTO_RECIPE_CHG_FAIL					= 596, 
	ER_SORTER_AUTO_RECIPE_CHG_TM_OVER		= 597, 
	ER_SORTER_AUTO_RECIPE_CHG_FAIL			= 598, 

	/////////////////////////////////////////////////////////////////////
	// 600~619 : Rail Part
	/////////////////////////////////////////////////////////////////////
	ER_RAIL_RCV_CYCLE_TM_OVER				= 600, 
	ER_RAIL_PCB_INFO_CYCLE_TM_OVER			= 601,
	ER_RAIL_LOT_MERGE_CYCLE_TM_OVER			= 602,
	ER_RAIL_LOT_START_CYCLE_TM_OVER			= 603,
	ER_RAIL_LOT_SPLIT_CYCLE_TM_OVER			= 604, // 추가

	ER_RAIL_EXIST							= 605, 
	ER_RAIL_EXIST_MEMORY_NOT_OFF			= 606, 
	ER_RAIL_EXIST_START_NOT_ON				= 607, 
	ER_RAIL_EXIST_START_NOT_OFF				= 608, 
	ER_RAIL_EXIST_MID_NOT_ON				= 609, 
	ER_RAIL_EXIST_MID_NOT_OFF				= 610, 
	ER_RAIL_EXIST_END_NOT_ON				= 611, 
	ER_RAIL_EXIST_END_NOT_OFF				= 612, 
	ER_RAIL_GRIPPER_EXIST_NOT_ON			= 613, 
	ER_RAIL_GRIPPER_EXIST_NOT_OFF			= 614,
	ER_RAIL_PCB_REMOVE						= 615,
	ER_RAIL_2D_READ_FAIL					= 616,
	ER_RAIL_2D_READ_TM_OVER					= 617,
	ER_RAIL_2D_READ_PART_DIFFERENT			= 618,
	ER_RAIL_MANUAL_LOT_PART_DIFFERENT		= 619,


	/////////////////////////////////////////////////////////////////////
	// 620~649 : Pnp Part
	/////////////////////////////////////////////////////////////////////	
	ER_IN_PNP_PCB_PICKUP_CYCLE_TM_OVER				= 620, 
	ER_IN_PNP_PCB_PUTDN_CYCLE_TM_OVER				= 621, 
	ER_IN_PNP_ADC_RAIL_PICKUP_CYCLE_TM_OVER			= 622,
	ER_IN_PNP_ADC_RAIL_PUTDN_CYCLE_TM_OVER			= 623,
	ER_IN_PNP_ADC_INDEX_PICKUP_CYCLE_TM_OVER		= 624, 
	ER_IN_PNP_ADC_INDEX_PUTDN_CYCLE_TM_OVER			= 625, 

	ER_IN_PNP_EXIST							= 635,
	ER_IN_PNP_EXIST_MEMORY_NOT_OFF			= 636, 
	ER_IN_PNP_EXIST_NOT_ON					= 637, 
	ER_IN_PNP_EXIST_NOT_OFF					= 638, 
	ER_IN_PNP_Z_NOT_READY_POS				= 639, 
	ER_IN_PNP_CLAMP_KIT_EXIST				= 640, 
	ER_ADC_IN_PNP_PCB_EXIST					= 641, 
	ER_ADC_IN_PNP_KIT_EXIST					= 642, 
	ER_ADC_IN_PNP_JOB_TYPE_EMPTY			= 643, 
	ER_ADC_IN_PNP_KIT_INFO_EMPTY			= 644, 
	ER_ADC_IN_PNP_EXIST_MEMORY_NOT_OFF		= 645,  
	ER_IN_PNP_KIT_EXIST_NOT_ON				= 646,
	ER_IN_PNP_KIT_EXIST_NOT_OFF				= 647,

	



	/////////////////////////////////////////////////////////////////////
	// 650~749 : Index01 ~ Index04
	/////////////////////////////////////////////////////////////////////
	ER_INDEX01_BIT_SUPPLY_BOX_NOT_EXIST		= 652, 
	ER_INDEX04_BIT_SUPPLY_BOX_NOT_EXIST		= 653, 
	ER_INDEX01_BIT_BOX_EMPTY				= 654, 
	ER_INDEX04_BIT_BOX_EMPTY				= 655, 
	ER_INDEX01_BIT_EJECT_BOX_NOT_EXIST		= 656, 
	ER_INDEX04_BIT_EJECT_BOX_NOT_EXIST		= 657, 
	ER_INDEX01_SCRAP_MEMORY_REMOVE			= 658,
	ER_INDEX02_SCRAP_MEMORY_REMOVE			= 659,
	ER_INDEX03_SCRAP_MEMORY_REMOVE			= 660,
	ER_INDEX04_SCRAP_MEMORY_REMOVE			= 661,
    ER_INDEX_OR_PICKER_KIT_TYPE_DIFFERENT	= 662,

	ER_INDEX02_BIT_SUPPLY_BOX_NOT_EXIST		= 664,
	ER_INDEX03_BIT_SUPPLY_BOX_NOT_EXIST		= 665,
	ER_INDEX02_BIT_BOX_EMPTY				= 666,
	ER_INDEX03_BIT_BOX_EMPTY				= 667,
	ER_INDEX02_BIT_EJECT_BOX_NOT_EXIST		= 668,
	ER_INDEX03_BIT_EJECT_BOX_NOT_EXIST		= 669,

	ER_SPINDLE_01_BIT_CHANGE_BUT_BIT_NOT_EMPTY	= 670, // 추가
	ER_SPINDLE_02_BIT_CHANGE_BUT_BIT_NOT_EMPTY	= 671, // 추가
	ER_SPINDLE_03_BIT_CHANGE_BUT_BIT_NOT_EMPTY	= 672, // 추가
	ER_SPINDLE_04_BIT_CHANGE_BUT_BIT_NOT_EMPTY	= 673, // 추가
	
	ER_INDEX01_NOT_IN_USE					= 675,
	ER_INDEX02_NOT_IN_USE					= 676,
	ER_INDEX03_NOT_IN_USE					= 677,
	ER_INDEX04_NOT_IN_USE					= 678,

	ER_INDEX_BIT_ALIGN_INDEX_02_EXIST_01			= 685,
	ER_INDEX_BIT_ALIGN_INDEX_02_EXIST_02			= 686,
	ER_INDEX_BIT_ALIGN_INDEX_03_EXIST_01			= 687,
	ER_INDEX_BIT_ALIGN_INDEX_03_EXIST_02			= 688,
	ER_INDEX_BIT_ALIGN_INDEX_02_NOT_EXIST_01		= 689,
	ER_INDEX_BIT_ALIGN_INDEX_02_NOT_EXIST_02		= 690,
	ER_INDEX_BIT_ALIGN_INDEX_03_NOT_EXIST_01		= 691,
	ER_INDEX_BIT_ALIGN_INDEX_03_NOT_EXIST_02		= 692,
	ER_SPINDLE_BIT_PRESS_DETECT_INDEX_02_BLUE_01	= 693, 
	ER_SPINDLE_BIT_PRESS_DETECT_INDEX_02_BLUE_02	= 694,
	ER_SPINDLE_BIT_PRESS_DETECT_INDEX_03_BLUE_01	= 695,
	ER_SPINDLE_BIT_PRESS_DETECT_INDEX_03_BLUE_02	= 696,

	ER_ADC_TOP_MZ_EXIST_STAGE_01			= 700,
    ER_ADC_TOP_MZ_EXIST_STAGE_02			= 701, 
    ER_ADC_TOP_MZ_EXIST_STAGE_03			= 702, 
    ER_ADC_TOP_MZ_EXIST_STAGE_04			= 703, 
    ER_ADC_TOP_MZ_EXIST_MASK_01				= 704, 
    ER_ADC_TOP_MZ_EXIST_MASK_02				= 705, 
    ER_ADC_TOP_MZ_EXIST_MASK_03				= 706, 
    ER_ADC_TOP_MZ_EXIST_MASK_04				= 707, 
    ER_ADC_TOP_MZ_EXIST_OUT_PICKER			= 708, 
    ER_ADC_BTM_MZ_EXIST_STAGE_01			= 709, 
    ER_ADC_BTM_MZ_EXIST_STAGE_02			= 710, 
    ER_ADC_BTM_MZ_EXIST_STAGE_03			= 711, 
    ER_ADC_BTM_MZ_EXIST_STAGE_04			= 712, 
    ER_ADC_BTM_MZ_EXIST_MASK_01				= 713, 
    ER_ADC_BTM_MZ_EXIST_MASK_02				= 714, 
    ER_ADC_BTM_MZ_EXIST_MASK_03				= 715, 
    ER_ADC_BTM_MZ_EXIST_MASK_04				= 716, 
    ER_ADC_BTM_MZ_EXIST_OUT_PICKER			= 717, 
    ER_ADC_TOP_MZ_NOT_EXIST_STAGE_01		= 718, 
    ER_ADC_TOP_MZ_NOT_EXIST_STAGE_02		= 719, 
    ER_ADC_TOP_MZ_NOT_EXIST_STAGE_03		= 720, 
    ER_ADC_TOP_MZ_NOT_EXIST_STAGE_04		= 721, 
    ER_ADC_TOP_MZ_NOT_EXIST_MASK_01			= 722, 
    ER_ADC_TOP_MZ_NOT_EXIST_MASK_02			= 723, 
    ER_ADC_TOP_MZ_NOT_EXIST_MASK_03			= 724, 
    ER_ADC_TOP_MZ_NOT_EXIST_MASK_04			= 725, 
    ER_ADC_TOP_MZ_NOT_EXIST_OUT_PICKER		= 726, 
    ER_ADC_BTM_MZ_NOT_EXIST_STAGE_01		= 727, 
    ER_ADC_BTM_MZ_NOT_EXIST_STAGE_02		= 728, 
    ER_ADC_BTM_MZ_NOT_EXIST_STAGE_03		= 729, 
    ER_ADC_BTM_MZ_NOT_EXIST_STAGE_04		= 730, 
    ER_ADC_BTM_MZ_NOT_EXIST_MASK_01			= 731, 
    ER_ADC_BTM_MZ_NOT_EXIST_MASK_02			= 732, 
    ER_ADC_BTM_MZ_NOT_EXIST_MASK_03			= 733, 
    ER_ADC_BTM_MZ_NOT_EXIST_MASK_04			= 734, 
    ER_ADC_BTM_MZ_NOT_EXIST_OUT_PICKER		= 735, 
    ER_ADC_RAIL_REMOVE_KIT					= 736, 
    ER_ADC_INDEX_01_PICKER_EXIST			= 737,
    ER_ADC_INDEX_01_MASK_N_PICKER_EXIST		= 738,
    ER_ADC_RAIL_KIT_JOB_TYPE_EMPTY			= 739,
    ER_ADC_RAIL_KIT_INFO_EMPTY				= 740,
	ER_ADC_GRIPPER_EXIST_NOT_ON				= 741,
    ER_ADC_GRIPPER_EXIST_NOT_OFF			= 742,
    ER_ADC_INDEX_01_MASK_N_MASK_PICKER_EXIST= 743, 
    ER_ADC_INDEX_02_MASK_N_MASK_PICKER_EXIST= 744, 
    ER_ADC_INDEX_03_MASK_N_MASK_PICKER_EXIST= 745, 
    ER_ADC_INDEX_04_MASK_N_MASK_PICKER_EXIST= 746, 


	/////////////////////////////////////////////////////////////////////
	// 750~849 : Router01 ~ Router04 
	/////////////////////////////////////////////////////////////////////
	ER_ROUTER_PRS_CYCLE_TM_OVER_01				= 750, 
	ER_ROUTER_PRS_CYCLE_TM_OVER_02				= 751, 
	ER_ROUTER_PRS_CYCLE_TM_OVER_03				= 752, 
	ER_ROUTER_PRS_CYCLE_TM_OVER_04				= 753, 
	ER_ROUTER_ROUTER_CYCLE_TM_OVER_01			= 754, 
	ER_ROUTER_ROUTER_CYCLE_TM_OVER_02			= 755, 
	ER_ROUTER_ROUTER_CYCLE_TM_OVER_03			= 756, 
	ER_ROUTER_ROUTER_CYCLE_TM_OVER_04			= 757, 
	ER_ROUTER_LIVE_VI_CYCLE_TM_OVER_01			= 758, 
	ER_ROUTER_LIVE_VI_CYCLE_TM_OVER_02			= 759, 
	ER_ROUTER_LIVE_VI_CYCLE_TM_OVER_03			= 760, 
	ER_ROUTER_LIVE_VI_CYCLE_TM_OVER_04			= 761, 
	ER_ROUTER_SPD_BIT_EJECT_CYCLE_TM_OVER_01	= 762, 
	ER_ROUTER_SPD_BIT_EJECT_CYCLE_TM_OVER_02	= 763, 
	ER_ROUTER_SPD_BIT_EJECT_CYCLE_TM_OVER_03	= 764, 
	ER_ROUTER_SPD_BIT_EJECT_CYCLE_TM_OVER_04	= 765, 
	ER_ROUTER_SPD_BIT_CLAMP_CYCLE_TM_OVER_01	= 766, 
	ER_ROUTER_SPD_BIT_CLAMP_CYCLE_TM_OVER_02	= 767, 
	ER_ROUTER_SPD_BIT_CLAMP_CYCLE_TM_OVER_03	= 768, 
	ER_ROUTER_SPD_BIT_CLAMP_CYCLE_TM_OVER_04	= 769, 
	ER_ROUTER_SPD_ESD_CHECK_CYCLE_TM_OVER_01	= 770, 
	ER_ROUTER_SPD_ESD_CHECK_CYCLE_TM_OVER_02	= 771, 
	ER_ROUTER_SPD_ESD_CHECK_CYCLE_TM_OVER_03	= 772, 
	ER_ROUTER_SPD_ESD_CHECK_CYCLE_TM_OVER_04	= 773, 
	ER_ROUTER_CYL_BIT_CLAMP_CYCLE_TM_OVER_F		= 774, 
	ER_ROUTER_CYL_BIT_CLAMP_CYCLE_TM_OVER_R		= 775,
	ER_ROUTER_CYL_BIT_CLAMP_COLOR_CHECK_FAIL_F  = 776,
	ER_ROUTER_CYL_BIT_CLAMP_COLOR_CHECK_FAIL_R  = 777,

	ER_ROUTER_CYL_BIT_ALIGN_CYCLE_TM_OVER_01		= 778, 
	ER_ROUTER_CYL_BIT_ALIGN_CYCLE_TM_OVER_02		= 779, 
	ER_ROUTER_CYL_BIT_ALIGN_CYCLE_TM_OVER_03		= 780, 
	ER_ROUTER_CYL_BIT_ALIGN_CYCLE_TM_OVER_04		= 781, 
	ER_ROUTER_CYL_SPD_BIT_VI_CYCLE_TM_OVER_01		= 782, 
	ER_ROUTER_CYL_SPD_BIT_VI_CYCLE_TM_OVER_02		= 783, 
	ER_ROUTER_CYL_SPD_BIT_VI_CYCLE_TM_OVER_03		= 784, 
	ER_ROUTER_CYL_SPD_BIT_VI_CYCLE_TM_OVER_04		= 785, 
	ER_ROUTER_CYL_SPD_BIT_VERIFY_CYCLE_TM_OVER_01	= 786, 
	ER_ROUTER_CYL_SPD_BIT_VERIFY_CYCLE_TM_OVER_02	= 787, 
	ER_ROUTER_CYL_SPD_BIT_VERIFY_CYCLE_TM_OVER_03	= 788, 
	ER_ROUTER_CYL_SPD_BIT_VERIFY_CYCLE_TM_OVER_04	= 789, 
	ER_ESD_CHECK_READ_FAIL_01					= 790, 
	ER_ESD_CHECK_READ_FAIL_02					= 791, 
	ER_ESD_CHECK_READ_FAIL_03					= 792, 
	ER_ESD_CHECK_READ_FAIL_04					= 793, 
	ER_ESD_CHECK_VALUE_LIMIT_01					= 794, 
	ER_ESD_CHECK_VALUE_LIMIT_02					= 795, 
	ER_ESD_CHECK_VALUE_LIMIT_03					= 796, 
	ER_ESD_CHECK_VALUE_LIMIT_04					= 797, 

	ER_ROUTER_CYL_BIT_CLAMP_COLOR_CHECK_CYCLE_TM_OVER		= 798,

	ER_ROUTER_Z_NOT_READY_POS_01				= 800,
	ER_ROUTER_Z_NOT_READY_POS_02				= 801,
	ER_ROUTER_Z_NOT_READY_POS_03				= 802,
	ER_ROUTER_Z_NOT_READY_POS_04				= 803,
	ER_ROUTER_BIT_BROKEN_3_CNT_01				= 804,
	ER_ROUTER_BIT_BROKEN_3_CNT_02				= 805,
	ER_ROUTER_BIT_BROKEN_3_CNT_03				= 806,
	ER_ROUTER_BIT_BROKEN_3_CNT_04				= 807,
	ER_ROUTER_BIT_DOWN_3_CNT_01					= 808,
	ER_ROUTER_BIT_DOWN_3_CNT_02					= 809,
	ER_ROUTER_BIT_DOWN_3_CNT_03					= 810,
	ER_ROUTER_BIT_DOWN_3_CNT_04					= 811,
	ER_ESD_CHECK_READ_TM_OVER					= 812,

	ER_SPINDLE_01_BIT_EJECT_FAIL				= 815,
	ER_SPINDLE_02_BIT_EJECT_FAIL				= 816,
	ER_SPINDLE_03_BIT_EJECT_FAIL				= 817,
	ER_SPINDLE_04_BIT_EJECT_FAIL				= 818,
	
	ER_SPINDLE_BIT_CLAMP_01									= 821,
	ER_SPINDLE_BIT_CLAMP_02									= 822,
	ER_SPINDLE_BIT_CLAMP_03									= 823,
	ER_SPINDLE_BIT_CLAMP_04									= 824,	
	ER_INDEX_BIT_ALIGN_INDEX_01_EXIST_01					= 825,
	ER_INDEX_BIT_ALIGN_INDEX_01_EXIST_02					= 826,
	ER_INDEX_BIT_ALIGN_INDEX_04_EXIST_01					= 827,
	ER_INDEX_BIT_ALIGN_INDEX_04_EXIST_02					= 828,
	ER_INDEX_BIT_ALIGN_INDEX_01_NOT_EXIST_01				= 829,
	ER_INDEX_BIT_ALIGN_INDEX_01_NOT_EXIST_02				= 830,
	ER_INDEX_BIT_ALIGN_INDEX_04_NOT_EXIST_01				= 831,
	ER_INDEX_BIT_ALIGN_INDEX_04_NOT_EXIST_02				= 832,
	ER_SPINDLE_BIT_PRESS_DETECT_INDEX_01_RED_01				= 833,
	ER_SPINDLE_BIT_PRESS_DETECT_INDEX_01_RED_02				= 834,
	ER_SPINDLE_BIT_PRESS_DETECT_INDEX_04_RED_01				= 835,
	ER_SPINDLE_BIT_PRESS_DETECT_INDEX_04_RED_02				= 836,

	ER_CYL_ROUTER_BIT_CHANGE_CLAMP_NOT_UP_01	= 837,
	ER_CYL_ROUTER_BIT_CHANGE_CLAMP_NOT_UP_02	= 838,
	ER_ROUTER_Y_SPINDLE_PITCH_ERR				= 839,
	ER_GERBER_LINE_TYPE_ERR						= 840,
	ER_NEED_BIT_CHANGE_01						= 841,
	ER_NEED_BIT_CHANGE_02						= 842,
	ER_NEED_BIT_CHANGE_03						= 843,
	ER_NEED_BIT_CHANGE_04						= 844,
	ER_SPINDLE_01_Z_ROUTER_POS_LIMIT			= 845,
	ER_SPINDLE_02_Z_ROUTER_POS_LIMIT			= 846,
	ER_SPINDLE_03_Z_ROUTER_POS_LIMIT			= 847,
	ER_SPINDLE_04_Z_ROUTER_POS_LIMIT			= 848,

	/////////////////////////////////////////////////////////////////////
	// 850~869 : Out Pnp
	/////////////////////////////////////////////////////////////////////
	ER_OUTPNP_PICKUP_CYCLE_TM_OVER				= 850,
	ER_OUTPNP_SCRAP_EJECT_CYCLE_TM_OVER			= 851, 
	ER_OUTPNP_PCB_PICKUP_CYCLE_TM_OVER			= 852, 
	ER_OUTPNP_PCB_PUTDN_CYCLE_TM_OVER			= 853, 
		
	ER_OUTPNP_ADC_PICKUP_CYCLE_TM_OVER			= 855,
	ER_OUTPNP_ADC_PUTDN_CYCLE_TM_OVER			= 856,

	ER_OUTPNP_SCRAP_EXIST						= 860, 
	ER_OUTPNP_PCB_EXIST							= 861,
	ER_OUTPNP_PCB_INDEX_NO						= 862,
	ER_OUTPNP_SORTER_PCB_INFO_TM_OVER			= 863,
	ER_OUTPNP_SORTER_PCB_INFO_FAIL				= 864,
	ER_ADC_OUTPNP_SCRAP_EXIST					= 865,
	ER_ADC_OUTPNP_PCB_EXIST						= 866,
	ER_MT_OUTPNP_Z_NOT_READY_POS				= 867, 



	/////////////////////////////////////////////////////////////////////
	// 870~899 : ADC
	/////////////////////////////////////////////////////////////////////
	ER_ADC_RAIL_FAIL								= 868, // 2022.03.10 ADC 에러 추가
	ER_ADC_RAIL_KIT_JOB_TYPE_DIFFERENT				= 869, 
    ER_ADC_EXIST									= 870, 
    ER_ADC_ALIGN_CYCLE_TM_OVER						= 871, 
    ER_ADC_GRIP_CYCLE_TM_OVER						= 872, 
    ER_ADC_PUSH_CYCLE_TM_OVER						= 873, 
	ER_ADC_RAIL_STATE_INFO_EMPTY					= 874, 
	ER_ADC_MGZ_JOB_TYPE_INCOLLECT					= 875,
	ER_ADC_MGZ_TOP_EXIST							= 876, 
	ER_ADC_MGZ_BTM_EXIST							= 877, 
	ER_ADC_MGZ_1D_READ_TM_OVER						= 878, 
	ER_ADC_MGZ_1D_READ_FAIL							= 879, 

	ER_ADC_KIT_JUT							= 880,
    ER_ADC_KIT_EXIST_STAGE_01				= 881, 
    ER_ADC_KIT_EXIST_STAGE_02				= 882, 
    ER_ADC_KIT_EXIST_STAGE_03				= 883, 
    ER_ADC_KIT_EXIST_STAGE_04				= 884, 
    ER_ADC_KIT_EXIST_MASK_01				= 885, 
    ER_ADC_KIT_EXIST_MASK_02				= 886, 
    ER_ADC_KIT_EXIST_MASK_03				= 887, 
    ER_ADC_KIT_EXIST_MASK_04				= 888, 
    ER_ADC_KIT_NOT_EXIST_STAGE_01			= 889, 
    ER_ADC_KIT_NOT_EXIST_STAGE_02			= 890, 
    ER_ADC_KIT_NOT_EXIST_STAGE_03			= 891, 
    ER_ADC_KIT_NOT_EXIST_STAGE_04			= 892, 
    ER_ADC_KIT_NOT_EXIST_MASK_01			= 893, 
    ER_ADC_KIT_NOT_EXIST_MASK_02			= 894, 
    ER_ADC_KIT_NOT_EXIST_MASK_03			= 895, 
    ER_ADC_KIT_NOT_EXIST_MASK_04			= 896, 
    ER_ADC_KIT_EXIST_OUTPNP					= 897, 
    ER_ADC_KIT_NOT_EXIST_OUTPNP				= 898, 
    ER_ADC_RAIL_REMOVE						= 899, 
    ER_ADC_KIT_EXIST_MASK_PICKER_01			= 900, 
    ER_ADC_KIT_EXIST_MASK_PICKER_02			= 901, 
    ER_ADC_KIT_EXIST_MASK_PICKER_03			= 902, 
    ER_ADC_KIT_EXIST_MASK_PICKER_04			= 903,

	ER_VI_INDEX01_IN_PRS_RESULT_LIMIT		= 904,
	ER_VI_INDEX02_IN_PRS_RESULT_LIMIT		= 905,
	ER_VI_INDEX03_IN_PRS_RESULT_LIMIT		= 906,
	ER_VI_INDEX04_IN_PRS_RESULT_LIMIT		= 907,

	/////////////////////////////////////////////////////////////////////
	// 900~929 : Vision
	/////////////////////////////////////////////////////////////////////
    ER_VI_NOT_READY							= 910, 
	ER_VI_ROUTER_PART_F_PRS_NOT_READY		= 911,
	ER_VI_ROUTER_PART_F_PRS_RESULT_TM_OVER	= 912,
	ER_VI_ROUTER_PART_F_PRS_FAIL			= 913, 
	ER_VI_ROUTER_PART_F_RESULT_XY_LIMIT		= 914, 
	ER_VI_ROUTER_PART_R_PRS_NOT_READY		= 915,
	ER_VI_ROUTER_PART_R_PRS_RESULT_TM_OVER	= 916,
	ER_VI_ROUTER_PART_R_PRS_FAIL			= 917, 
	ER_VI_ROUTER_PART_R_RESULT_XY_LIMIT		= 918, 
	ER_VI_INDEX01_BLOCK_PRS_RESULT_LIMIT	= 919,
	ER_VI_INDEX02_BLOCK_PRS_RESULT_LIMIT	= 920,
	ER_VI_INDEX03_BLOCK_PRS_RESULT_LIMIT	= 921,
	ER_VI_INDEX04_BLOCK_PRS_RESULT_LIMIT	= 922,
	ER_VI_ROUTER_BTM_NOT_READY				= 923,
	ER_VI_ROUTER_BTM_RESULT_TM_OVER			= 924,
	ER_VI_ROUTER_BTM_FAIL					= 925,


	/////////////////////////////////////////////////////////////////////
	// 930~959 : Gem or 통신 등
	/////////////////////////////////////////////////////////////////////
	ER_LOT_SPLIT_COUNT_EMPTY				= 926, // 추가

	ER_SPLIT_LOT_START_TM_OVER				= 927, // 추가
	ER_SPLIT_LOT_START_FAIL					= 928, // 추가
	ER_FDC_REMOTE_STOP						= 929, // 추가
	ER_PCB_INFO_TM_OVER						= 930,
	ER_PCB_INFO_FAIL						= 931,
	ER_LOT_START_TM_OVER					= 932,
	ER_LOT_START_FAIL						= 933,
	ER_LOT_MERGE_TM_OVER					= 934,
	ER_LOT_MERGE_FAIL						= 935,
	ER_LOT_SPLIT_TM_OVER					= 936, // 추가
	ER_LOT_SPLIT_FAIL						= 937, // 추가

	ER_LOT_QTY_OVER_1MGZ_MAX_QTY			= 938, 
	ER_LOT_QTY_OVER_TRAY1_PROD_QTY			= 939, 
	ER_LOT_INFO_NOT_EXIST_LOADER			= 940,
	ER_LOT_INFO_NOT_EXIST_PCB				= 941,
	ER_LOT_INFO_NOT_EXIST_RAIL				= 942,
	ER_LOT_INFO_NOT_EXIST_INPNP				= 943,
	ER_LOT_INFO_NOT_EXIST_INDEX01			= 944,
	ER_LOT_INFO_NOT_EXIST_INDEX02			= 945,
	ER_LOT_INFO_NOT_EXIST_INDEX03			= 946,
	ER_LOT_INFO_NOT_EXIST_INDEX04			= 947,
	ER_LOT_INFO_NOT_EXIST_OUTPNP			= 948,
	ER_LOT_SPLIT_ID_EMPTY					  = 949, // 추가
 	ER_LOT_INFO_PART_ID_DIFFERENT			  = 950,
	ER_LOT_INFO_PART_ID_NOT_EXIST			  = 951,
	ER_LOT_INFO_MERGE_LOT_ID_DIFFERENT		  = 952,
	ER_LOT_INFO_MERGE_LOT_ID_NOT_EXIST		  = 953,
	ER_LOT_INFO_MERGE_LOT_ID_SAME			  = 954, 
	ER_LOT_HISTORY_MERGE_LOT_ID_NOT_EXIST	  = 955, 
	ER_LOT_HISTORY_LAST_CARRIER_ID_NOT_EXIST  = 956, 
	ER_LOT_HISTORY_LAST_LOT_QTY_OVER		  = 957, 
	ER_LOT_END_LAST_LOT_QTY_DIFFERENT		  = 958, 
	ER_LAST_LOT_QTY_DIFFERENT				  = 959,


	/////////////////////////////////////////////////////////////////////
	// 960~ : Sorter Interface
	/////////////////////////////////////////////////////////////////////
	ER_SORTER_ERROR							= 960,
		
	ER_ADC_MGZ_TOP_STAGE_01_GRIP_JAM		= 981, // Kit 간섭으로 Grip시에 Grip 하단에 Kit이 있으면 안됨
	ER_ADC_MGZ_TOP_STAGE_02_GRIP_JAM		= 982, 
	ER_ADC_MGZ_TOP_STAGE_03_GRIP_JAM		= 983, 
	ER_ADC_MGZ_TOP_STAGE_04_GRIP_JAM		= 984, 
	ER_ADC_MGZ_TOP_MASK_01_GRIP_JAM			= 985, 
	ER_ADC_MGZ_TOP_MASK_02_GRIP_JAM			= 986, 
	ER_ADC_MGZ_TOP_MASK_03_GRIP_JAM			= 987, 
	ER_ADC_MGZ_TOP_MASK_04_GRIP_JAM			= 988, 
	ER_ADC_MGZ_BTM_STAGE_01_GRIP_JAM		= 989, 
	ER_ADC_MGZ_BTM_STAGE_02_GRIP_JAM		= 990, 
	ER_ADC_MGZ_BTM_STAGE_03_GRIP_JAM		= 991, 
	ER_ADC_MGZ_BTM_STAGE_04_GRIP_JAM		= 992, 
	ER_ADC_MGZ_BTM_MASK_01_GRIP_JAM			= 993, 
	ER_ADC_MGZ_BTM_MASK_02_GRIP_JAM			= 994, 
	ER_ADC_MGZ_BTM_MASK_03_GRIP_JAM			= 995, 
	ER_ADC_MGZ_BTM_MASK_04_GRIP_JAM			= 996, 
	
	ER_ALL_HOME								= 999,

	ER_MAX									= 1000,
};


enum WrName
{
	WR_LOT_END				= 1,
	WR_PAUSED_STOP			= 2,
	WR_DRY_RUN				= 3,
	WR_DOOR_OPEN			= 4,
	WR_LOADER_SAFETYBEAM	= 5,
	WR_ALL_HOME_PROGRESS	= 6,
	WR_ADC_FINISH			= 7,
	WR_LOADER_MGZ_FULL		= 8,
	WR_LOADER_PCB_JAM		= 9, // 추가
	WR_SCRAP_BOX_NOT_EXIST	= 10,
	WR_SCRAP_BOX_SAFETYBEAM	= 11,

	WR_SORTER_AUTO_RUN		= 12,

	////////////////////////////////////////////
	// Motor Not Ready
	WR_NOT_READY_MT_INDEX_X_01		= 20,  
	WR_NOT_READY_MT_INDEX_X_02		= 21,  
	WR_NOT_READY_MT_INDEX_X_03		= 22,  
	WR_NOT_READY_MT_INDEX_X_04		= 23, 
	WR_NOT_READY_MT_INDEX_T_01		= 24, 
	WR_NOT_READY_MT_INDEX_T_02		= 25, 
	WR_NOT_READY_MT_INDEX_T_03		= 26, 
	WR_NOT_READY_MT_INDEX_T_04		= 27, 
	WR_NOT_READY_MT_ROUTER_Y_01		= 28,  
	WR_NOT_READY_MT_ROUTER_Y_02		= 29,  
	WR_NOT_READY_MT_ROUTER_W_01		= 30,  
	WR_NOT_READY_MT_ROUTER_W_02		= 31,  
	WR_NOT_READY_MT_SPINDLE_Z_01	= 32, 
	WR_NOT_READY_MT_SPINDLE_Z_02	= 33,       
	WR_NOT_READY_MT_SPINDLE_Z_03	= 34,       
	WR_NOT_READY_MT_SPINDLE_Z_04	= 35,
	WR_NOT_READY_MT_MGZ_LOAD_Z		= 36, 
	WR_NOT_READY_MT_PUSHER_X		= 37, 
	WR_NOT_READY_MT_RAIL_GRIPPER_X	= 38, 
	WR_NOT_READY_MT_LD_Y			= 39,  
	WR_NOT_READY_MT_LD_Z			= 40,  
	WR_NOT_READY_MT_OUTPNP_Y		= 41, 
	WR_NOT_READY_MT_OUTPNP_Z		= 42, 
	WR_NOT_READY_MT_OUTPNP_X		= 43, 
	WR_NOT_READY_MT_INPNP_CLAMP_Y	= 44, 
	WR_NOT_READY_MT_INPNP_Y			= 45, 
	WR_NOT_READY_MT_INPNP_Z			= 46, 
	WR_NOT_READY_MT_ADC_Z			= 47, 
	WR_NOT_READY_MT_ADC_X			= 48, 


	////////////////////////////////////////////
	// Index Move시 Motor 조건
	WR_MT_INPNP_Z_NOT_READY_POS		= 100,
	WR_MT_SPINDLE_Z_01_NOT_READY_POS= 101,
	WR_MT_SPINDLE_Z_02_NOT_READY_POS= 102,
	WR_MT_SPINDLE_Z_03_NOT_READY_POS= 103,
	WR_MT_SPINDLE_Z_04_NOT_READY_POS= 104,
	WR_MT_ROUTER_Y_01_NOT_READY_POS	= 105,
	WR_MT_ROUTER_Y_02_NOT_READY_POS	= 106,
	WR_MT_OUTPNP_Z_NOT_READY_POS	= 107,
	WR_MT_PUSHER_X_NOT_BWD_POS		= 108,
	WR_MT_LD_Y_NOT_READY_POS		= 109,
	WR_MT_OUTPNP_X_NOT_READY_POS	= 110,

	////////////////////////////////////////////
	// Index Move시 Cyl 조건
	WR_CYL_ROUTER_BIT_CHANGE_CLAMP_01_NOT_UP = 200,
	WR_CYL_ROUTER_BIT_CHANGE_CLAMP_02_NOT_UP = 201,
	WR_CYL_MASK_PICKER_01_NOT_UP = 202,
	WR_CYL_MASK_PICKER_02_NOT_UP = 203,
	WR_CYL_MASK_PICKER_03_NOT_UP = 204,
	WR_CYL_MASK_PICKER_04_NOT_UP = 205,
	////////////////////////////////////////////
	// 센서 조건
	WR_LD_MZ_CLAMP_PCB_JAM_NOT_OFF	= 300,
	WR_RAIL_EXIST_START_NOT_OFF		= 301,
	WR_RAIL_EXIST_MID_NOT_OFF		= 302,
	WR_RAIL_EXIST_MID2_NOT_OFF		= 303,
	WR_RAIL_EXIST_END_NOT_OFF		= 304,
	WR_RAIL_GRIPPER_EXIST_NOT_OFF	= 305,
	WR_RAIL_EXIST_MEMORY_NOT_OFF	= 306,

	WR_SPINDLE_TIME_OVER_F			= 307,
	WR_SPINDLE_TIME_OVER_R			= 308,

	WR_OUTPNP_PAD_LIFE_COUNT_OVER	= 309, 


};


#endif // _ERRORNAMEDEF_H_